INSERT INTO monsters (id, name, description, boss_text, navi_text, hp, damage, dot, weakness, strength, image_url) VALUES
(1, 
'Deku Baba (Withered)', 
'A shriveled and weakened form of the standard Deku Baba. Unlike its more aggressive counterpart, the Withered Deku Baba remains stationary and only flinches when struck. Defeating it is easy, as a single strike will cause it to drop either a Deku Stick or a Deku Nut.', 
'',
'Though it looks withered it will hurt you if you touch it!',
'1',
'1',
'0',
'Sword attacks',
'Very weak',
'/images/enemies/deku_baba_withered.png'),
(2,
'Deku Baba',
'A hostile, plant-like enemy that springs from the ground and attempts to bite Link when he comes near. Defeating a Deku Baba usually yields a Deku Stick or a Deku Nut. They can be easily dispatched with a sword slash, and timing your attack correctly will prevent them from lunging.',
'',
'Hit it when it lunges at you, and it will stand upright. Cut it quickly to get a Deku Stick!',
'1',
'1',
'0',
'Sword attacks',
'Very weak',
'/images/enemies/deku_baba.png'),
(3,
'Skullwalltula',
'A hostile, plant-like enemy that springs from the ground and attempts to bite Link when he comes near. Defeating a Deku Baba usually yields a Deku Stick or a Deku Nut. They can be easily dispatched with a sword slash, and timing your attack correctly will prevent them from lunging.',
'',
'Be careful not to touch it!',
'1',
'1',
'0',
'Sword attacks, projectile attacks',
'Very weak',
'/images/enemies/skullwalltula.png'),
(4,
'Deku Scrub',
'Small, plant-like creatures that hide in Deku Flowers and pop out to spit Deku Nuts at intruders. When Link approaches, the Deku Scrub will shoot a projectile at him and then retreat back into its flower. To defeat a Deku Scrub, Link must deflect its projectile back at it using his shield, causing the Deku Scrub to emerge, stunned and defenseless. In most cases, after being hit, the Deku Scrub will offer information or flee.',
'',
'It will hide in the grass if you get close to it. Bounce the nuts it spits back at it!',
'1',
'1',
'0',
'Deflect its projectile',
'Very weak',
'/images/enemies/deku_scrub.png'),
(5,
'Big Skulltula',
'A large, spider-like enemy with a hard, skull-like shell on its back. Big Skulltulas hang from ceilings or drop down in front of Link to block his path. They are immune to frontal attacks due to their armored shell, but they expose their vulnerable underbelly when they turn around, which can be struck to defeat them. Big Skulltulas can be easily defeated by waiting for them to turn or by using weapons like the Hookshot to target their weak spot directly.',
'',
'Its soft belly is its weak point!',
'2',
'2',
'0',
'Sword attacks',
'Weak',
'/images/enemies/big_skulltula.png'),
(6,
'Gohma Larva',
'Small, spider-like creatures that hatch from the eggs laid by Queen Gohma. They are fast and aggressive, swarming Link as soon as they emerge. Despite their numbers, Gohma Larvae are weak and can be defeated with a single strike from most weapons. They are primarily found in the boss fight with Queen Gohma, where they can be a distraction if not dealt with quickly.',
'',
'Look out when it gets ready to pounce!',
'2',
'1',
'0',
'Sword attacks',
'Weak',
'/images/enemies/gohma_larva.png'),
(7,
'(Queen) Gohma',
'Gohma is a large, menacing arachnid and the boss of the Inside the Deku Tree dungeon. Known as the Parasitic Armored Arachnid, she has a single, large, glowing eye that serves as her weak point. Gohma attacks by crawling on the ceiling and dropping eggs that hatch into Gohma Larvae. Her primary attack involves charging at Link or swiping with her claws. To defeat Gohma, Link must use a ranged weapon like the Slingshot to stun her by hitting her eye when it turns red, then quickly strike her with his sword while she is incapacitated. After a few cycles of this, she is defeated.',
'Parasitic Armored Arachnid',
'It''s one of the parasitic monsters inside the Deku Tree! Its eye is vulnerable when it''s red!',
'10',
'2',
'0',
'Sword attacks, projectile attacks, deku nuts',
'Medium',
'/images/enemies/gohma.png'),
(8,
'Business Scrub',
'A type of Deku Scrub that, rather than being purely hostile, is more interested in doing business. When approached, a Business Scrub will shoot Deku Nuts at Link, similar to a regular Deku Scrub. However, after Link deflects the attack back with his shield, the Business Scrub will cease its aggression and offer to sell items, such as Deku Nuts, Deku Sticks, or other useful supplies, often at a high price. They can be found in various locations throughout Hyrule, often hidden in secret grottos or dungeons.',
'',
'If you get close to it, it will hide in the grass...',
'1',
'1',
'0',
'Deflect its projectile',
'Very weak',
'/images/enemies/business_scrub.png'),
(9,
'Red Tektite',
'A spider-like creature that moves by hopping on its four legs, commonly found in rocky or mountainous areas. Red Tektites are agile and will attempt to hop towards Link to attack him. They are less aggressive than their blue counterparts but can still be a nuisance, especially when encountered in groups. Red Tektites are vulnerable to most of Lin''s weapons, and a few sword strikes or a well-placed ranged attack will defeat them. They are typically found in areas like Death Mountain or near Goron City.',
'',
'Lock on to it as it jumps with Z Targeting!',
'2',
'2',
'0',
'Sword attacks',
'Weak',
'/images/enemies/red_tektite.png'),
(10,
'Poe',
'Ghostly apparitions that are often encountered in the Forest Temple and occasionally other haunted areas. Poes are elusive and can become invisible at will, making them difficult to attack directly. They typically hover in the air and attack Link with fireballs or a similar energy projectile. To defeat a Poe, Link must use the Lock-on targeting system to track its movements, wait for it to become visible, and then strike it with his sword or other weapons. Once defeated, Poes drop a Poe Soul, which is used for trading with the big Poe hunter, or, in some cases, specific rewards.',
'',
'If you stare at it with Z Targeting, it will disappear...',
'8',
'2',
'0',
'Sword attacks, projectile attacks',
'Weak',
'/images/enemies/poe.png');